server:
  port: 8080

spring:
  application:
    name: accounts
  profiles:
    active: prod

  # ---- DataSource / JPA ----
  datasource:
    url: jdbc:mysql://localhost:3308/accountsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # ---- Config Server ----
  config:
    import: "configserver:http://configserver-ms:8071/"

  # ---- RabbitMQ ----
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
